### PR TITLE
Gdl tutorial2

### PR DESCRIPTION
**Pull request by Gabri95**

### CODE REVIEW

**Comment by Gabri95** [comment]
I included both the tutorial with solutions and the one unanswered.
In the `index.rst`, I only included the complete notebook; I am not sure where we can link to the unanswered tutorial.

I also tried to compile the documentation myself, but it seems that `nbsphinx` has some issues with creating the right sections and table of content. Is that only my problem?

Gabriele

**Comment by Gabri95** [comment]
ok, I should have fixed the sections issues, thanks for spotting the problem!

The only problem left for me is including a multi-line equation.
I am currently using `\begin{align} ... \end{align}`, but that doesn't seem to be properly rendered by `nbsphinx`.
Do you have any recommendations?

Gabriele

**Comment by phlippe** [comment]
Great, can you update the pull request with the new notebook? I can look into the align problem, we might simply need to add some extra spaces or newlines (sphinx has some weird requirements there sometimes)

**Comment by phlippe** [comment]
Thanks! I tried running it on GCollab, but couldn't install the escnn package:
```
ERROR: Could not find a version that satisfies the requirement escnn (from versions: none)
ERROR: No matching distribution found for escnn
```
Any idea how to install the package correctly? Same when I do it locally.

**Comment by Gabri95** [comment]
mhmm that is weird.. I can do it on GCollab without any issue.
I also made a copy of the GCollab notebook I shared and I could run it smoothly

**Comment by phlippe** [comment]
Ok, I tried it again and this time pip can find the package. That probably was just an issue for an hour.
I was able to run the notebook now, but an assertion fails in cell 81:
```
x = torch.randn(1, 1, 23, 23)
x = feat_type_in(x)

y = equivariant_so2_model(x)

# check equivariance to N=16 rotations
N = 16


for i in range(N):
    g = G.element(i*2*np.pi/N)
    x_transformed = x.transform(g)
    y_from_x_transformed = equivariant_so2_model(x_transformed)

    y_transformed_from_x = y.transform(g)

    assert torch.allclose(y_from_x_transformed.tensor, y_transformed_from_x.tensor, atol=1e-3), g

```
The assert statement works for i=0, but fails for i=1. The max distance between the two tensors is about 5.5. I assume that should not happen, right?

**Comment by Gabri95** [comment]
Yeah that error is supposed to happen, check the question in the next cell

**Comment by Gabri95** [comment]
Mhm, ok I'll try to generate and store the weights tomorrow

**Comment by phlippe** [comment]
> Yeah that error is supposed to happen, check the question in the next cell

Ok, could we replace this assert statement with a print-and-loop-break instead? Otherwise, the notebook fails every time you want to run it from top-to-bottom, which will likely also confuse some students.

**Comment by Gabri95** [comment]
Yeah seems a good idea, will fix that too. I will send a new version in a bit with all the changes

**Comment by Gabri95** [comment]
I fixed everything, but I am having a hard time to merge the conflicts inside the jupyter notebook :/ 
Maybe it's easier if I just keep my version and then I manually add your changes

**Comment by Gabri95** [comment]
btw, where should I store the trained models?
I currently use  "../../saved_models/DL2/GDL" since I saw it in the first tutorial, but I do not see this path on github. Should I upload the trained models or will you rerun my notebook on the RTD server to regenerate them?

**Comment by phlippe** [comment]
Ah, right, sorry for the merge conflict. Hope the changes were not too many :/

We collect all stored models in this repo: https://github.com/phlippe/saved_models. Does the notebook currently save the checkpoints when you run it from top-to-bottom? Because then the easiest is probably that I run it once more on my local machine, and push the saved models to that repo once done (I will verify with you that the results are as expected)

**Comment by Gabri95** [comment]
yep it does, so you can just run it once indeed (although you have to manually comment out the code which tries to download them).

I still have not managed to merge them ahah

**Comment by phlippe** [comment]
Can you convert the notebook to a python file (`jupyter nbconvert --to script [YOUR_NOTEBOOK].ipynb`) and push the python file here? If you let me know which cells were changed, it's probably faster if I replace them with the new code in the python file

**Comment by Gabri95** [comment]
Ok done (sorry for coming back to you so late)

The changes are:
- in the first code block, I added some code to cache and download the stored weights/accuracies
- fixed code block 81, adding the try/except around the assertion error
- rename function in code blocks 90 and 91 (`test_model_single_image`)
- code block 92 is doing the caching of the training weights (and added `test` function)
- block 93 specifies the checkpoint path and test the model again
- block 94 now is doing caching of the final accuracies
- block 95 specifies the caching path for the accuraices
- block 98 specifies the checkpoint path, test the model again and specifies the caching path for the accuracies
- fix a typo in "Steerable CNNs" in the conclusion block

**Comment by phlippe** [comment]
Thanks a lot! I integrated the changes, and it all runs smoothly now. :) 
The tutorial is now integrated on the website: https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/DL2/Geometric_deep_learning/tutorial2_steerable_cnns.html
Let me know in case you spot anything being off

**Comment by Gabri95** [comment]
Nice, thanks!!

I see a couple of issues though:
- in the colab, the font of the plots looks a bit "funny" and hard to read. Is that because of some matplotlib setting? (I see you set something about svg and pdf)
- in the RTD version, some equations are not rendered correctly.  It looks like the problem happens when there is an equation with $$ $$ immediately followed by normal text. Maybe a new line between them will solve it?

**Comment by phlippe** [comment]
Thanks for pointing those out! I hope to have fixed all math rendering problems now. 
Regarding the plots: I am not sure if we see the same rendering. This is a screenshot of the equivariant vs conventional CNNs plot I get when running it on Google Colab:
colab_screenshot_DL2_GDL2
Which font would you like to have changed? The settings `set_matplotlib_formats('svg', 'pdf')` let all plots being rendered as 'svg' figures in the notebook, allowing us to have uncompressed, light-weight vector graphics on the RTD website. One difference to png is that the figures are rendered slightly larger, but I think that is not what you mean, right? The second setting, `matplotlib.rcParams['lines.linewidth'] = 2.0`, increases the default line width to 2, since a line width of 1 looks quite thin on the RTD website. As a comparison, the screenshot below is the rendering on matplotlib without any of the above matplotlib settings:
colab_screenshot_DL2_GLD2_png

**Comment by Gabri95** [comment]
Nice, yeah all math formatting issues seem gone, thanks!


Mhmm.. that's weird, this is what I see on Google Collab: 

image

Maybe it's only my problem? This was not the case in my GCollab notebook though

**Comment by phlippe** [comment]
Hm, it seems that svgs might not be supported for you there. I checked it on Linux (Ubuntu) - Chrome, Mac - Chrome and Mac - Safari, and all show the correct font. Which operating system and browser are you using? 
Can you also check what happens if you comment out the maptlotlib setting block, i.e.
```
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
matplotlib.rcParams['lines.linewidth'] = 2.0
```
Then Colab should render it as png images as before.

**Comment by Gabri95** [comment]
I am also using Max + Chrome, but I might have an older version of Chrome.
Anyways, removing those lines solve the problem.

It doesn't seem a big issue anyways, we can just leave it as it is

**Comment by phlippe** [comment]
I've added a comment to remove the respective lines in case students experience the same issues as you have. I think that should make it clear

**Comment by Gabri95** [comment]
sounds good, thanks a lot!

**Pull request merged**
