### PR TITLE
Add Deep Probabilistic Models I tutorial

### PR DESCRIPTION
**Pull request by Roxot**

### CODE REVIEW

**Comment by phlippe** [comment]
Hi Bryan, could you adjust the first cell after the title to the [template](https://github.com/phlippe/uvadlc_notebooks/blob/master/docs/tutorial_notebooks/DL2/template/TemplateNotebook.ipynb) with a badge to the github, collab (update the link to where the tutorial will be), and author list?

Do you have any pretrained models that are loaded? If so, let me know to add them to our separate repo for that.

The tutorial currently compiles with errors for the website:
```
/home/phillip/Documents/DL_course/notebook_test/docs/tutorial_notebooks/DL2/deep_probabilistic_models_I/tutorial_1.ipynb:1877: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/phillip/Documents/DL_course/notebook_test/docs/tutorial_notebooks/DL2/deep_probabilistic_models_I/tutorial_1.ipynb:1879: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/phillip/Documents/DL_course/notebook_test/docs/tutorial_notebooks/DL2/deep_probabilistic_models_I/tutorial_1.ipynb:2437: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/phillip/Documents/DL_course/notebook_test/docs/tutorial_notebooks/DL2/deep_probabilistic_models_I/tutorial_1.ipynb:2439: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/phillip/Documents/DL_course/notebook_test/docs/tutorial_notebooks/DL2/deep_probabilistic_models_I/tutorial_1.ipynb:2865: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/phillip/Documents/DL_course/notebook_test/docs/tutorial_notebooks/DL2/deep_probabilistic_models_I/tutorial_1.ipynb:2867: WARNING: Definition list ends without a blank line; unexpected unindent.
``` 
Sphinx requires a blank line after an itemize or enumerate, and math equations should not have a space before the closing `$`. Could you check for that?

**Comment by Roxot** [comment]
Hi Phlippe,

Thanks, I see that indeed some of the math equations are not properly rendering, but I cannot figure out why. This cell for example has trouble rendering the `align` section correctly:

```
### 7.2 Poisson

Here we design a probabilistic model for an ordinal response variable $Y$ given a document $x$, for which we choose to model with a Poisson pmf:

\begin{align}
    Y|X=x &\sim \mathrm{Poisson}(g(x; \theta)) \\
    \mathbf u &= \mathrm{encode}_D(x; \theta_{\text{enc}}) \\
    s &= \mathrm{affine}_1(\mathbf u; \theta_{\text{out}}) \\
    g(x; \theta) &= \mathrm{softplus}(s)
\end{align}

The Poisson rate parameter must be strictly positive, thus we use a softplus output.
```

**Comment by Roxot** [comment]
> Hi Phlippe,
> 
> Thanks, I see that indeed some of the math equations are not properly rendering, but I cannot figure out why. This cell for example has trouble rendering the `align` section correctly:
> 
> ```
> ### 7.2 Poisson
> 
> Here we design a probabilistic model for an ordinal response variable $Y$ given a document $x$, for which we choose to model with a Poisson pmf:
> 
> \begin{align}
>     Y|X=x &\sim \mathrm{Poisson}(g(x; \theta)) \\
>     \mathbf u &= \mathrm{encode}_D(x; \theta_{\text{enc}}) \\
>     s &= \mathrm{affine}_1(\mathbf u; \theta_{\text{out}}) \\
>     g(x; \theta) &= \mathrm{softplus}(s)
> \end{align}
> 
> The Poisson rate parameter must be strictly positive, thus we use a softplus output.
> ```

I figured it out, Sphinx doesn't like the whitespaces in front of the lines. I'll update the PR.

**Comment by Roxot** [comment]
I updated the PR, for me it compiled without warnings now and all the equations are rendered properly. I also added links to the lecture recordings and reported the notebook authors.

**Pull request merged**
